version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    # depends_on:
    #   - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=flores.radyalabs.id;Port=5432;Database=iaif_catalog;User Id=postgres;Password=N3wDVr9efTBpffidb7sh4uIQjlot0TN6ju*;
    networks:
      - iaif-network

  # db:
  #   image: postgres:16
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=iaif_catalog
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - iaif-network

networks:
  iaif-network:
    driver: bridge

volumes:
  postgres-data: